# Generated by Django 4.2.6 on 2024-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ManyToManyField(to='role.role'),
        ),
    ]
