# Generated by Django 4.2.6 on 2024-03-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
