# Generated by Django 4.2.6 on 2024-03-11 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_role', to='groups.groups')),
                ('permissions', models.ManyToManyField(to='permissions.permissions')),
            ],
        ),
    ]
